server:
  port: 8080
  servlet:
    context-path: /api/v1/
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: console
  datasource:
    username: postgres
    password: 16798520
    url: jdbc:postgresql://localhost:5432/OBSS

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true




